# Generated by Django 6.0.1 on 2026-03-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_tithe', models.BooleanField(default=False)),
                ('is_offering', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='meetingcollection',
            name='total_first_fruits',
        ),
        migrations.RemoveField(
            model_name='meetingcollection',
            name='total_offering',
        ),
        migrations.RemoveField(
            model_name='meetingcollection',
            name='total_seed_offering',
        ),
        migrations.RemoveField(
            model_name='meetingcollection',
            name='total_tithe',
        ),
        migrations.AddField(
            model_name='meetingcollection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingcollection',
            name='name_of_counter',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.collectioncategory')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.meetingcollection')),
            ],
            options={
                'ordering': ['category__name'],
                'unique_together': {('collection', 'category')},
            },
        ),
    ]
