# Generated by Django 6.0.1 on 2026-02-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('SUNDAY_SERVICE', 'Sunday Service'), ('MIDWEEK', 'Midweek Service'), ('PRAYER', 'Prayer Meeting'), ('YOUTH', 'Youth Meeting'), ('OTHER', 'Other')], max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('adult_female', models.PositiveIntegerField(default=0)),
                ('adult_male', models.PositiveIntegerField(default=0)),
                ('teen_female', models.PositiveIntegerField(default=0)),
                ('teen_male', models.PositiveIntegerField(default=0)),
                ('children_female', models.PositiveIntegerField(default=0)),
                ('children_male', models.PositiveIntegerField(default=0)),
                ('preacher', models.CharField(blank=True, max_length=200)),
                ('title_of_msg', models.CharField(blank=True, max_length=255)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('activity_type', 'group', 'date')},
            },
        ),
    ]
