# Generated by Django 6.0.1 on 2026-02-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_type', models.CharField(choices=[('MINISTRY', 'Ministry Group'), ('SERVICE', 'Service Group')], max_length=10)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_groups', to='members.member')),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='members.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
