# Generated by Django 6.0.1 on 2026-02-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['group_type', 'name']},
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Optional: group leader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_groups', to='members.member'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='church_groups', to='members.member'),
        ),
    ]
