# Generated by Django 6.0.1 on 2026-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone1', models.CharField(blank=True, max_length=30)),
                ('phone2', models.CharField(blank=True, max_length=30)),
                ('born_again', models.BooleanField(default=False)),
                ('joining', models.BooleanField(default=False)),
                ('need_visitation', models.BooleanField(default=False)),
                ('prayer_request', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
