# Generated by Django 6.0.1 on 2026-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_no', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('age_category', models.CharField(choices=[('CHILD', 'Child'), ('TEEN', 'Teen'), ('ADULT', 'Adult')], max_length=10)),
                ('date_of_join', models.DateField()),
                ('date_of_renewal', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('house_no', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone1', models.CharField(max_length=30)),
                ('phone2', models.CharField(blank=True, max_length=30)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
